#AWS authentication
access_key: 'YOUR-AWS-ACCESS-KEY'
secret_key: 'YOUR-AWS-SECRET-KEY'
account: 'YOUR-AWS-ACCOUNT'
key_path: 'COMPLETE-PATH-TO-YOUR-PATH' #ex:'/Users/steveodom/Documents/Projects/ec2/auth/'
keypair_name: 'rails-server' 

#s3 Related
image_bucket: "YOUR-S3-BUCKET" #where are your ec2 AMI images stored#

#ec2 Related
url: 'YOUR-EC2-URL-RETURNED-AFTER-LAUNCH' #ex'domU-12-31-34-00-00-71.usma2.compute.amazonaws.com'

# Users on Server:
user: 'ec2admin' #this user should initially be 'ec2admin' to login the first time to the instance
user_password: 'ec2admin' 
user_secondary: 'YOUR_USER'
user_secondary_password: 'YOUR-PASSWORD'

#database
db_adapter: 'mysql'
db_user: 'YOUR-DB-USER' #should match your database.yml
db_password: 'YOUR-DB-PASSWORD' #should match your database.yml

# SVN Repository
svn_user: 'YOUR-SVN-USER'
svn_password: 'YOUR-SVN-USER-PASSWORD'
svn_repository: 'YOUR-REPOSITORY-URL' #ex:'http://quizical.unfuddle.com/svn/quizical/'

# options:
application: 'YOUR-APPLICATION-NAME'
server: 'litespeed' #options: add mongrel and lighttpd configurations later
mode: 'production'
#cache: 'cache/www.quizical.net/landing/' #optional. For s3cache plugin
use_ssl: false

# litespeed related
ls_bin: '/opt/lsws/bin/lswsctrl'

# Packages Locations
ruby_gems: 'http://rubyforge.org/frs/download.php/11289/rubygems-0.9.0.tgz'